export {default as HomePage} from './home/home-page'
export {default as AboutPage} from './about/about-page'
export {CourseListPage} from './course'
export {CourseSingleShowPage} from './course'
export {default as WishListPage} from './profile/wish/wish-list-page'
